// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rema1000.API.Data;

namespace Rema1000.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210521155819_DataSeedConfiguration")]
    partial class DataSeedConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rema1000.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Mejeri produkter, såsom mælk, ost, fløde osv.",
                            Name = "Mejeri"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Vand, Sodavand, Øl, Energidrikke m.m.",
                            Name = "Læskedrikke"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Rugbrød, toastbrød, franskbrød m.m.",
                            Name = "Brød"
                        });
                });

            modelBuilder.Entity("Rema1000.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<double>("Unit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            CategoryId = 2,
                            Desc = "Sukkerfri Cola!",
                            Name = "Pepsi Max",
                            Price = 15.949999999999999,
                            Stock = 500,
                            SupplierId = 3,
                            Unit = 1.5
                        },
                        new
                        {
                            Id = 2,
                            Amount = 6,
                            CategoryId = 2,
                            Desc = "Øl med 1.5% alkohol!",
                            Name = "Heineken",
                            Price = 36.950000000000003,
                            Stock = 150,
                            SupplierId = 3,
                            Unit = 0.33000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            CategoryId = 3,
                            Desc = "Rugbrød med store kerner.",
                            Name = "Rugbrød",
                            Price = 11.949999999999999,
                            Stock = 50,
                            SupplierId = 2,
                            Unit = 0.20000000000000001
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1,
                            CategoryId = 3,
                            Desc = "Sundt brød!",
                            Name = "Sandwhichbrød",
                            Price = 20.949999999999999,
                            Stock = 25,
                            SupplierId = 2,
                            Unit = 0.5
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1,
                            CategoryId = 1,
                            Desc = "Mælk du kan drikke.",
                            Name = "Sødmælk",
                            Price = 8.9499999999999993,
                            Stock = 100,
                            SupplierId = 1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1,
                            CategoryId = 1,
                            Desc = "Ost til din madpakke.",
                            Name = "Ost",
                            Price = 22.949999999999999,
                            Stock = 300,
                            SupplierId = 1,
                            Unit = 0.20000000000000001
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1,
                            CategoryId = 2,
                            Desc = "Kakao du kan drikke.",
                            Name = "Kakao",
                            Price = 16.949999999999999,
                            Stock = 500,
                            SupplierId = 1,
                            Unit = 1.0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1,
                            CategoryId = 3,
                            Desc = "Nyt fra Arla, de kan også lave brød!",
                            Name = "Arla Brød",
                            Price = 24.949999999999999,
                            Stock = 50,
                            SupplierId = 1,
                            Unit = 1.0
                        });
                });

            modelBuilder.Entity("Rema1000.Shared.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Arla mejeri produkter og produktion.",
                            Name = "Arla"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Brød, brød og brød.",
                            Name = "Schulstad"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Produktion af Sodavand, øl og andre læskedrikke.",
                            Name = "Royal Unibrew"
                        });
                });

            modelBuilder.Entity("Rema1000.Shared.Models.Product", b =>
                {
                    b.HasOne("Rema1000.Shared.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rema1000.Shared.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
